version: '3.7'
services:
  nginx:
    container_name: cont_nginx2
    hostname: cont_nginx2
    build: ./containers/nginx
    ports:
      - '80:80'
    networks:
      - net-serv
    volumes:
      - './src/:/var/www'
      - './config-nginx/:/etc/nginx/conf.d'
  php:
    container_name: cont_php2
    hostname: cont_php2
    build: ./containers/php
    networks:
      - net-serv
    volumes:
      - './src/:/var/www'
  mysql:
    container_name: cont_mysql2
    hostname: cont_mysql2
    build: ./containers/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - net-serv

networks:
  net-serv:
