apiVersion: v1
kind: Secret
metadata:
  name: mysqldb-secret
type: Opaque
data:
  mongo-root-username: cm9vdA== # Dans les Secrets, les infos doivent être en base64 --> $> echo -n 'username' | bas64
  mongo-root-password: cm9vdA== # $> echo -n 'password' | base64